const form=document.getElementById('createForm'), inputs=[...document.querySelectorAll('.photo-input')], photos=[null,null,null,null];
const $=id=>document.getElementById(id);
function ready(){return window.SUPABASE_URL.startsWith('http')&&!window.SUPABASE_PUBLISHABLE_KEY.startsWith('PASTE_')}
function headers(json=false){return {'apikey':window.SUPABASE_PUBLISHABLE_KEY,'Authorization':`Bearer ${window.SUPABASE_PUBLISHABLE_KEY}`,...(json?{'Content-Type':'application/json'}:{})}}
function id(){return crypto.randomUUID().replaceAll('-','').slice(0,10)}
async function hash(v){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function resize(file,max=1600,q=.82){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext('2d').drawImage(im,0,0,c.width,c.height);c.toBlob(b=>b?res(b):rej(), 'image/jpeg',q)};im.onerror=rej;im.src=r.result};r.onerror=rej;r.readAsDataURL(file)})}
inputs.forEach(inp=>inp.addEventListener('change',async()=>{const f=inp.files[0],box=inp.closest('.upload');if(!f)return;if(!f.type.startsWith('image/')){alert('Please choose an image.');inp.value='';return}try{photos[+inp.dataset.index]=await resize(f);box.style.backgroundImage=`url(${URL.createObjectURL(photos[+inp.dataset.index])})`;box.classList.add('has-photo')}catch{alert('Could not process that photo.');inp.value=''}}));
async function upload(blob,path){const r=await fetch(`${window.SUPABASE_URL}/storage/v1/object/birthday-photos/${path}`,{method:'POST',headers:{...headers(),'x-upsert':'false','Content-Type':'image/jpeg'},body:blob});if(!r.ok)throw new Error(await r.text());return `${window.SUPABASE_URL}/storage/v1/object/public/birthday-photos/${path}`}
form.addEventListener('submit',async e=>{e.preventDefault();if(!ready()){alert('Open js/config.js and add your Supabase URL + anon key first. See SETUP.md.');return}const name=$('name').value.trim(),pass=$('passcode').value.trim(),message=$('message').value.trim();if(pass.length<4)return alert('Use at least 4 characters for the passcode.');if(photos.some(x=>!x))return alert('Please upload all four photos.');const btn=$('createBtn');btn.disabled=true;btn.textContent='Uploading memories…';$('status').textContent='Please keep this tab open while the four photos upload.';try{const sid=id(),urls=[];for(let i=0;i<4;i++){urls.push(await upload(photos[i],`${sid}/${i}.jpg`));$('status').textContent=`Uploading photo ${i+1} of 4…`}const row={id:sid,name,message:message||'May your days be filled with happiness, laughter and beautiful memories.',passcode_hash:await hash(pass),photo1:urls[0],photo2:urls[1],photo3:urls[2],photo4:urls[3]};const r=await fetch(`${window.SUPABASE_URL}/rest/v1/birthday_surprises`,{method:'POST',headers:{...headers(true),'Prefer':'return=minimal'},body:JSON.stringify(row)});if(!r.ok)throw new Error(await r.text());const link=`${location.href.replace(/create\.html.*$/i,'')}surprise.html?id=${sid}`;$('shareLink').value=link;$('openBtn').href=link;$('result').classList.remove('hidden');form.classList.add('hidden');$('status').textContent='';window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'})}catch(err){console.error(err);alert('Could not create the surprise. Check SETUP.md and your Supabase policies.');}finally{btn.disabled=false;btn.textContent='Create Share Link ✨'}});
$('copyBtn').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('shareLink').value)}catch{$('shareLink').select();document.execCommand('copy')}$('copyBtn').textContent='Copied ✓';setTimeout(()=>$('copyBtn').textContent='Copy',1600)});$('newBtn').addEventListener('click',()=>location.reload());
