const $=id=>document.getElementById(id), locked=$('lockedView'), reveal=$('revealView');
function headers(){return {'apikey':window.SUPABASE_PUBLISHABLE_KEY,'Authorization':`Bearer ${window.SUPABASE_PUBLISHABLE_KEY}`}}
async function hash(v){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
const sid=new URLSearchParams(location.search).get('id');
async function load(){if(!sid){return invalid()}try{const r=await fetch(`${window.SUPABASE_URL}/rest/v1/birthday_surprises?id=eq.${encodeURIComponent(sid)}&select=name,message,passcode_hash,photo1,photo2,photo3,photo4`,{headers:headers()});if(!r.ok)throw 0;const rows=await r.json();if(!rows.length)return invalid();const d=rows[0];$('unlockBtn').onclick=()=>unlock(d);$('codeInput').onkeydown=e=>{if(e.key==='Enter')unlock(d)};$('beginReveal').onclick=()=>startReveal(d)}catch(e){invalid()}}
function invalid(){locked.innerHTML=`<div class="lock-icon">💔</div><p class="eyebrow">SURPRISE NOT FOUND</p><h1>This link isn't <em>available.</em></h1><p>It may be incomplete, expired, or not set up yet.</p><a class="primary full center" href="create.html">Create a Surprise</a>`}
async function unlock(d){const input=$('codeInput').value;if(await hash(input)!==d.passcode_hash){$('errorMsg').textContent='That code does not match. Try again 💗';$('codeInput').animate([{transform:'translateX(-7px)'},{transform:'translateX(7px)'},{transform:'translateX(0)'}],{duration:260});return}$('personName').textContent=d.name;$('finalName').textContent=d.name;$('introMessage').textContent=d.message;$('finalText').textContent=d.message;[d.photo1,d.photo2,d.photo3,d.photo4].forEach((u,i)=>$("photo"+i).src=u);locked.classList.add('hidden');reveal.classList.remove('hidden');document.title=`Happy Birthday ${d.name} 🎂`;particles()}
function startReveal(){const g=$('gallery');g.classList.remove('hidden');g.classList.add('play');$('beginReveal').style.display='none';setTimeout(()=>{$('finalMessage').classList.remove('hidden');$('finalMessage').scrollIntoView({behavior:'smooth',block:'center'})},6200)}
function particles(){const box=$('particles');['♥','♡','✦','✧','❀'].forEach((s,k)=>{for(let i=0;i<7;i++){const p=document.createElement('span');p.textContent=s;p.className='particle';p.style.left=Math.random()*100+'%';p.style.animationDelay=Math.random()*5+'s';p.style.animationDuration=6+Math.random()*5+'s';box.appendChild(p)}})}
load();
